// <auto-generated />
using DhomeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DhomeApp.Data.Migrations
{
    [DbContext(typeof(DbContextDhomeApp))]
    partial class DbContextDhomeAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DhomeApp.Entity.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("AppointmentDate")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("appointmentDate");

                    b.Property<int>("CustomerId")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idCustomer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<int>("EmployeeId")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idEmployee");

                    b.Property<int>("IdPaymentMethod")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idPaymentMethod");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("Valorization")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("valorization");

                    b.HasKey("AppointmentId");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("DhomeApp.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cellphone")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Cellphone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("Dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Firstname");

                    b.Property<int>("IdAccount")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idAccount");

                    b.Property<int>("IdCity")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idCity");

                    b.Property<int>("IdDistrict")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idDistrict");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Lastname");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DhomeApp.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cellphone")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Cellphone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("Dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Firstname");

                    b.Property<int>("IdAccount")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idAccount");

                    b.Property<int>("IdCity")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idCity");

                    b.Property<int>("IdDistrict")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idDistrict");

                    b.Property<int>("IdSpecialty")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("idSpecialty");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Lastname");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
